---
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/main/nautobot-plugin-ssot-panorama/docs"
site_name: "NautobotSSoTPanorama Documentation"
site_url: "https://nautobot-plugin-ssot-panorama.readthedocs.io/"
repo_url: "https://github.com/networktocode/nautobot-plugin-ssot-panorama"
python:
  install:
    - requirements: "docs/requirements.txt"
theme:
  name: "readthedocs"
  navigation_depth: 4
  hljs_languages:
    - "django"
    - "yaml"
extra_css:
  - "extra.css"
markdown_extensions:
  - "admonition"
  - toc:
      permalink: true
nav:
  - Introduction: "index.md"
