---
version: '3.5'
services:
  batfish:
    container_name: batfish
    image: batfish/batfish
    ports:
      - 9997:9997
      - 9996:9996
    volumes:
      - ./data:/tmp/data
    restart: unless-stopped
