---
- name: "10000 - GENERATE CONFIGURATIONS"
  hosts: "webinar"
  connection: "local"
  gather_facts: false
  tasks:
    - name: "10010 - GENERATE CONFIGURATIONS"
      template:
        src: "/local/config_gen/templates/{{ inventory_hostname }}.j2"
        dest: "/local/config_gen/data/configs/{{ inventory_hostname }}.cfg"
